// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GeometryGraph Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using GeometryGraph.Runtime.Attributes;
using GeometryGraph.Runtime.Geometry;
using UnityCommons;

namespace GeometryGraph.Runtime.Graph {
    [SourceClass("GeometryGraph.Runtime::GeometryGraph.Runtime.Graph::CirclePrimitiveNode")]
    public partial class CirclePrimitiveNode : RuntimeNode {
        public RuntimePort RadiusPort { get; }
        public RuntimePort PointsPort { get; }
        public RuntimePort ResultPort { get; }

        public CirclePrimitiveNode(string guid) : base(guid) {
            RadiusPort = RuntimePort.Create(PortType.Float, PortDirection.Input, this);
            PointsPort = RuntimePort.Create(PortType.Integer, PortDirection.Input, this);
            ResultPort = RuntimePort.Create(PortType.Geometry, PortDirection.Output, this);
        }

        public void UpdateRadius(float newValue) {
            if(Math.Abs(Radius - newValue) < Constants.FLOAT_TOLERANCE) return;
            Radius = newValue;
            CalculateResult();
            NotifyPortValueChanged(ResultPort);
        }

        public void UpdatePoints(int newValue) {
            if(Points == newValue) return;
            Points = newValue;
            CalculateResult();
            NotifyPortValueChanged(ResultPort);
        }

        protected override object GetValueForPort(RuntimePort port) {
            if (port == ResultPort) return Result;
            return null;
        }

        protected override void OnPortValueChanged(Connection connection, RuntimePort port) {
            if (port == ResultPort) return;
            if (port == RadiusPort) {
                var newValue = GetValue(connection, Radius);
                newValue = newValue.MinClamped(Constants.MIN_CIRCULAR_GEOMETRY_RADIUS);
                if(Math.Abs(Radius - newValue) < Constants.FLOAT_TOLERANCE) return;
                Radius = newValue;
                CalculateResult();
                NotifyPortValueChanged(ResultPort);
            } else if (port == PointsPort) {
                var newValue = GetValue(connection, Points);
                newValue = newValue.Clamped(Constants.MIN_CIRCULAR_GEOMETRY_POINTS, Constants.MAX_CIRCULAR_GEOMETRY_POINTS);
                if(Points == newValue) return;
                Points = newValue;
                CalculateResult();
                NotifyPortValueChanged(ResultPort);
            }
        }

        public override string GetCustomData() {
            return new JArray {
                Radius,
                Points,
            }.ToString(Formatting.None);
        }

        public override void SetCustomData(string data) {
            JArray array = JArray.Parse(data);
            Radius = array.Value<float>(0);
            Points = array.Value<int>(1);

            CalculateResult();
            NotifyPortValueChanged(ResultPort);
        }
    }
}