// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GeometryGraph Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using GeometryGraph.Runtime.Attributes;
using JetBrains.Annotations;
using Unity.Mathematics;
using GeometryGraph.Runtime.Serialization;

namespace GeometryGraph.Runtime.Graph {
    [SourceClass("GeometryGraph.Runtime::GeometryGraph.Runtime.Graph::VectorBranchNode")]
    public partial class VectorBranchNode : RuntimeNode {
        public RuntimePort ConditionPort { get; }
        public RuntimePort IfTruePort { get; }
        public RuntimePort IfFalsePort { get; }
        public RuntimePort ResultPort { get; }

        public VectorBranchNode(string guid) : base(guid) {
            ConditionPort = RuntimePort.Create(PortType.Boolean, PortDirection.Input, this);
            IfTruePort = RuntimePort.Create(PortType.Vector, PortDirection.Input, this);
            IfFalsePort = RuntimePort.Create(PortType.Vector, PortDirection.Input, this);
            ResultPort = RuntimePort.Create(PortType.Vector, PortDirection.Output, this);
        }

        public void UpdateCondition(bool newValue) {
            if(Condition == newValue) return;
            Condition = newValue;
            NotifyPortValueChanged(ResultPort);
        }

        public void UpdateIfTrue(float3 newValue) {
            IfTrue = newValue;
            NotifyPortValueChanged(ResultPort);
        }

        public void UpdateIfFalse(float3 newValue) {
            IfFalse = newValue;
            NotifyPortValueChanged(ResultPort);
        }

        protected override object GetValueForPort(RuntimePort port) {
            if (port == ResultPort) return Condition ? IfTrue : IfFalse;
            return null;
        }

        protected override void OnPortValueChanged(Connection connection, RuntimePort port) {
            if (port == ResultPort) return;
            if (port == ConditionPort) {
                var newValue = GetValue(ConditionPort, Condition);
                if(Condition == newValue) return;
                Condition = newValue;
                NotifyPortValueChanged(ResultPort);
            } else if (port == IfTruePort) {
                var newValue = GetValue(IfTruePort, IfTrue);
                IfTrue = newValue;
                NotifyPortValueChanged(ResultPort);
            } else if (port == IfFalsePort) {
                var newValue = GetValue(IfFalsePort, IfFalse);
                IfFalse = newValue;
                NotifyPortValueChanged(ResultPort);
            }
        }

        public override string GetCustomData() {
            return new JArray {
                Condition ? 1 : 0,
                JsonConvert.SerializeObject(IfTrue, float3Converter.Converter),
                JsonConvert.SerializeObject(IfFalse, float3Converter.Converter),
            }.ToString(Formatting.None);
        }

        public override void SetCustomData(string data) {
            JArray array = JArray.Parse(data);
            Condition = array.Value<int>(0) == 1;
            IfTrue = JsonConvert.DeserializeObject<float3>(array.Value<string>(1), float3Converter.Converter);
            IfFalse = JsonConvert.DeserializeObject<float3>(array.Value<string>(2), float3Converter.Converter);

            NotifyPortValueChanged(ResultPort);
        }
    }
}