// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GeometryGraph Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using GeometryGraph.Runtime.Attributes;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;

namespace GeometryGraph.Runtime.Graph {
    [SourceClass("GeometryGraph.Runtime::GeometryGraph.Runtime.Graph::FloatValueNode")]
    public partial class FloatValueNode : RuntimeNode {
        public RuntimePort ValuePort { get; }

        public FloatValueNode(string guid) : base(guid) {
            ValuePort = RuntimePort.Create(PortType.Float, PortDirection.Output, this);
        }

        public void UpdateValue(float newValue) {
            if(Math.Abs(Value - newValue) < Constants.FLOAT_TOLERANCE) return;
            Value = newValue;
            NotifyPortValueChanged(ValuePort);
        }

        protected override object GetValueForPort(RuntimePort port) {
            if (port == ValuePort) return Value;
            return null;
        }

        protected override void OnPortValueChanged(Connection connection, RuntimePort port) {
            if (port == ValuePort) return;
        }

        public override string GetCustomData() {
            return new JArray {
                Value,
            }.ToString(Formatting.None);
        }

        public override void SetCustomData(string data) {
            JArray array = JArray.Parse(data);
            Value = array.Value<float>(0);

            NotifyPortValueChanged(ValuePort);
        }
    }
}