// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GeometryGraph Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using GeometryGraph.Runtime.Attributes;
using JetBrains.Annotations;

namespace GeometryGraph.Runtime.Graph {
    [SourceClass("GeometryGraph.Runtime::GeometryGraph.Runtime.Graph::IntegerValueNode")]
    public partial class IntegerValueNode : RuntimeNode {
        public RuntimePort ValuePort { get; }

        public IntegerValueNode(string guid) : base(guid) {
            ValuePort = RuntimePort.Create(PortType.Integer, PortDirection.Output, this);
        }

        public void UpdateValue(int newValue) {
            if(Value == newValue) return;
            Value = newValue;
            NotifyPortValueChanged(ValuePort);
        }

        protected override object GetValueForPort(RuntimePort port) {
            if (port == ValuePort) return Value;
            return null;
        }

        protected override void OnPortValueChanged(Connection connection, RuntimePort port) {
            if (port == ValuePort) return;
        }

        public override string GetCustomData() {
            return new JArray {
                Value,
            }.ToString(Formatting.None);
        }

        public override void SetCustomData(string data) {
            JArray array = JArray.Parse(data);
            Value = array.Value<int>(0);

            NotifyPortValueChanged(ValuePort);
        }
    }
}