// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GeometryGraph Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using GeometryGraph.Runtime.Attributes;
using JetBrains.Annotations;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;

namespace GeometryGraph.Runtime.Graph {
    [SourceClass("GeometryGraph.Runtime::GeometryGraph.Runtime.Graph::CompareFloatNode")]
    public partial class CompareFloatNode : RuntimeNode {
        public RuntimePort TolerancePort { get; }
        public RuntimePort APort { get; }
        public RuntimePort BPort { get; }
        public RuntimePort ResultPort { get; }

        public CompareFloatNode(string guid) : base(guid) {
            TolerancePort = RuntimePort.Create(PortType.Float, PortDirection.Input, this);
            APort = RuntimePort.Create(PortType.Float, PortDirection.Input, this);
            BPort = RuntimePort.Create(PortType.Float, PortDirection.Input, this);
            ResultPort = RuntimePort.Create(PortType.Boolean, PortDirection.Output, this);
        }

        public void UpdateTolerance(float newValue) {
            if(Math.Abs(Tolerance - newValue) < Constants.FLOAT_TOLERANCE) return;
            Tolerance = newValue;
            NotifyPortValueChanged(ResultPort);
        }

        public void UpdateA(float newValue) {
            if(Math.Abs(A - newValue) < Constants.FLOAT_TOLERANCE) return;
            A = newValue;
            NotifyPortValueChanged(ResultPort);
        }

        public void UpdateB(float newValue) {
            if(Math.Abs(B - newValue) < Constants.FLOAT_TOLERANCE) return;
            B = newValue;
            NotifyPortValueChanged(ResultPort);
        }

        public void UpdateOperation(CompareFloatNode_CompareOperation newValue) {
            if(Operation == newValue) return;
            Operation = newValue;
            NotifyPortValueChanged(ResultPort);
        }

        protected override object GetValueForPort(RuntimePort port) {
            if (port == ResultPort) {
                return Operation switch {
                    CompareFloatNode_CompareOperation.LessThan => A < B,
                    CompareFloatNode_CompareOperation.LessThanOrEqual => A <= B,
                    CompareFloatNode_CompareOperation.GreaterThan => A > B,
                    CompareFloatNode_CompareOperation.GreaterThanOrEqual => A >= B,
                    CompareFloatNode_CompareOperation.Equal => MathF.Abs(A - B) < Tolerance,
                    CompareFloatNode_CompareOperation.NotEqual => MathF.Abs(A - B) > Tolerance,
                    _ => throw new ArgumentOutOfRangeException(nameof(Operation), Operation, null)
                };
            }
            return null;
        }

        protected override void OnPortValueChanged(Connection connection, RuntimePort port) {
            if (port == ResultPort) return;
            if (port == TolerancePort) {
                var newValue = GetValue(connection, Tolerance);
                if(Math.Abs(Tolerance - newValue) < Constants.FLOAT_TOLERANCE) return;
                Tolerance = newValue;
                NotifyPortValueChanged(ResultPort);
            } else if (port == APort) {
                var newValue = GetValue(connection, A);
                if(Math.Abs(A - newValue) < Constants.FLOAT_TOLERANCE) return;
                A = newValue;
                NotifyPortValueChanged(ResultPort);
            } else if (port == BPort) {
                var newValue = GetValue(connection, B);
                if(Math.Abs(B - newValue) < Constants.FLOAT_TOLERANCE) return;
                B = newValue;
                NotifyPortValueChanged(ResultPort);
            }
        }

        public override string GetCustomData() {
            return new JArray {
                Tolerance,
                A,
                B,
                (int)Operation,
            }.ToString(Formatting.None);
        }

        public override void SetCustomData(string data) {
            JArray array = JArray.Parse(data);
            Tolerance = array.Value<float>(0);
            A = array.Value<float>(1);
            B = array.Value<float>(2);
            Operation = (CompareFloatNode_CompareOperation) array.Value<int>(3);

            NotifyPortValueChanged(ResultPort);
        }
    }
}