// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GeometryGraph Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using GeometryGraph.Runtime.Attributes;
using GeometryGraph.Runtime.Geometry;
using GeometryGraph.Runtime.Serialization;
using Unity.Mathematics;

namespace GeometryGraph.Runtime.Graph {
    [SourceClass("GeometryGraph.Runtime::GeometryGraph.Runtime.Graph::BoundingBoxNode")]
    public partial class BoundingBoxNode : RuntimeNode {
        public RuntimePort InputPort { get; }
        public RuntimePort BoundingBoxPort { get; }
        public RuntimePort MinPort { get; }
        public RuntimePort MaxPort { get; }

        public BoundingBoxNode(string guid) : base(guid) {
            InputPort = RuntimePort.Create(PortType.Geometry, PortDirection.Input, this);
            BoundingBoxPort = RuntimePort.Create(PortType.Geometry, PortDirection.Output, this);
            MinPort = RuntimePort.Create(PortType.Vector, PortDirection.Output, this);
            MaxPort = RuntimePort.Create(PortType.Vector, PortDirection.Output, this);
        }

        protected override object GetValueForPort(RuntimePort port) {
            if (port == BoundingBoxPort) return BoundingBox;
            if (port == MinPort) return Min;
            if (port == MaxPort) return Max;
            return null;
        }

        protected override void OnPortValueChanged(Connection connection, RuntimePort port) {
            if (port == BoundingBoxPort || port == MinPort || port == MaxPort) return;
            if (port == InputPort) {
                var newValue = GetValue(connection, Input);
                Input = newValue;
                CalculateResult();
                NotifyPortValueChanged(BoundingBoxPort);
                NotifyPortValueChanged(MinPort);
                NotifyPortValueChanged(MaxPort);
            }
        }
    }
}