// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GeometryGraph Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using GeometryGraph.Runtime.Attributes;
using GeometryGraph.Runtime.Geometry;
using System.Collections.Generic;
using System.Linq;

namespace GeometryGraph.Runtime.Graph {
    [SourceClass("GeometryGraph.Runtime::GeometryGraph.Runtime.Graph::JoinGeometryNode")]
    public partial class JoinGeometryNode : RuntimeNode {
        public RuntimePort InputPort { get; }
        public RuntimePort ResultPort { get; }

        public JoinGeometryNode(string guid) : base(guid) {
            InputPort = RuntimePort.Create(PortType.Geometry, PortDirection.Input, this);
            ResultPort = RuntimePort.Create(PortType.Geometry, PortDirection.Output, this);
        }

        protected override object GetValueForPort(RuntimePort port) {
            if (port == ResultPort) return Result;
            return null;
        }

        protected override void OnPortValueChanged(Connection connection, RuntimePort port) {
            if (port == ResultPort) return;
            if (port == InputPort) {
                CalculateResult();
                NotifyPortValueChanged(ResultPort);
            }
        }

        public override void SetCustomData(string data) {
            CalculateResult();
            NotifyPortValueChanged(ResultPort);
        }
    }
}