// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GeometryGraph Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using GeometryGraph.Runtime.Attributes;
using GeometryGraph.Runtime.AttributeSystem;
using GeometryGraph.Runtime.Geometry;
using GeometryGraph.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Unity.Mathematics;

namespace GeometryGraph.Runtime.Graph {
    [SourceClass("GeometryGraph.Runtime::GeometryGraph.Runtime.Graph::TransformGeometryNode")]
    public partial class TransformGeometryNode : RuntimeNode {
        public RuntimePort InputPort { get; }
        public RuntimePort TranslationPort { get; }
        public RuntimePort RotationPort { get; }
        public RuntimePort ScalePort { get; }
        public RuntimePort ResultPort { get; }

        public TransformGeometryNode(string guid) : base(guid) {
            InputPort = RuntimePort.Create(PortType.Geometry, PortDirection.Input, this);
            TranslationPort = RuntimePort.Create(PortType.Vector, PortDirection.Input, this);
            RotationPort = RuntimePort.Create(PortType.Vector, PortDirection.Input, this);
            ScalePort = RuntimePort.Create(PortType.Vector, PortDirection.Input, this);
            ResultPort = RuntimePort.Create(PortType.Geometry, PortDirection.Output, this);
        }

        public void UpdateTranslation(float3 newValue) {
            if(math.distancesq(Translation, newValue) < Constants.FLOAT_TOLERANCE * Constants.FLOAT_TOLERANCE) return;
            Translation = newValue;
            CalculateResult();
            NotifyPortValueChanged(ResultPort);
        }

        public void UpdateRotation(float3 newValue) {
            if(math.distancesq(Rotation, newValue) < Constants.FLOAT_TOLERANCE * Constants.FLOAT_TOLERANCE) return;
            Rotation = newValue;
            CalculateResult();
            NotifyPortValueChanged(ResultPort);
        }

        public void UpdateScale(float3 newValue) {
            if(math.distancesq(Scale, newValue) < Constants.FLOAT_TOLERANCE * Constants.FLOAT_TOLERANCE) return;
            Scale = newValue;
            CalculateResult();
            NotifyPortValueChanged(ResultPort);
        }

        protected override object GetValueForPort(RuntimePort port) {
            if (port == ResultPort) return Result;
            return null;
        }

        protected override void OnPortValueChanged(Connection connection, RuntimePort port) {
            if (port == ResultPort) return;
            if (port == InputPort) {
                Input = GetValue(connection, GeometryData.Empty);
                CalculateResult();
                NotifyPortValueChanged(ResultPort);
            } else if (port == TranslationPort) {
                var newValue = GetValue(connection, Translation);
                if(math.distancesq(Translation, newValue) < Constants.FLOAT_TOLERANCE * Constants.FLOAT_TOLERANCE) return;
                Translation = newValue;
                CalculateResult();
                NotifyPortValueChanged(ResultPort);
            } else if (port == RotationPort) {
                var newValue = GetValue(connection, Rotation);
                if(math.distancesq(Rotation, newValue) < Constants.FLOAT_TOLERANCE * Constants.FLOAT_TOLERANCE) return;
                Rotation = newValue;
                CalculateResult();
                NotifyPortValueChanged(ResultPort);
            } else if (port == ScalePort) {
                var newValue = GetValue(connection, Scale);
                if(math.distancesq(Scale, newValue) < Constants.FLOAT_TOLERANCE * Constants.FLOAT_TOLERANCE) return;
                Scale = newValue;
                CalculateResult();
                NotifyPortValueChanged(ResultPort);
            }
        }

        public override string GetCustomData() {
            return new JArray {
                JsonConvert.SerializeObject(Translation, float3Converter.Converter),
                JsonConvert.SerializeObject(Rotation, float3Converter.Converter),
                JsonConvert.SerializeObject(Scale, float3Converter.Converter),
            }.ToString(Formatting.None);
        }

        public override void SetCustomData(string data) {
            JArray array = JArray.Parse(data);
            Translation = JsonConvert.DeserializeObject<float3>(array.Value<string>(0), float3Converter.Converter);
            Rotation = JsonConvert.DeserializeObject<float3>(array.Value<string>(1), float3Converter.Converter);
            Scale = JsonConvert.DeserializeObject<float3>(array.Value<string>(2), float3Converter.Converter);

            CalculateResult();
            NotifyPortValueChanged(ResultPort);
        }
    }
}