// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GeometryGraph Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using GeometryGraph.Runtime.Attributes;
using GeometryGraph.Runtime.AttributeSystem;
using GeometryGraph.Runtime.Geometry;
using Unity.Mathematics;
using UnityEngine;
using GeometryGraph.Runtime.Serialization;

namespace GeometryGraph.Runtime.Graph {
    [SourceClass("GeometryGraph.Runtime::GeometryGraph.Runtime.Graph::TranslatePointNode")]
    public partial class TranslatePointNode : RuntimeNode {
        public RuntimePort InputPort { get; }
        public RuntimePort TranslationPort { get; }
        public RuntimePort AttributeNamePort { get; }
        public RuntimePort ResultPort { get; }

        public TranslatePointNode(string guid) : base(guid) {
            InputPort = RuntimePort.Create(PortType.Geometry, PortDirection.Input, this);
            TranslationPort = RuntimePort.Create(PortType.Vector, PortDirection.Input, this);
            AttributeNamePort = RuntimePort.Create(PortType.String, PortDirection.Input, this);
            ResultPort = RuntimePort.Create(PortType.Geometry, PortDirection.Output, this);
        }

        public void UpdateInput(GeometryData newValue) {
            Input = newValue;
            Calculate();
            NotifyPortValueChanged(ResultPort);
        }

        public void UpdateTranslation(float3 newValue) {
            if(math.distancesq(Translation, newValue) < Constants.FLOAT_TOLERANCE * Constants.FLOAT_TOLERANCE) return;
            Translation = newValue;
            Calculate();
            NotifyPortValueChanged(ResultPort);
        }

        public void UpdateAttributeName(string newValue) {
            if(string.Equals(AttributeName, newValue, StringComparison.InvariantCulture)) return;
            AttributeName = newValue;
            Calculate();
            NotifyPortValueChanged(ResultPort);
        }

        public void UpdateMode(TranslatePointNode_Mode newValue) {
            if(Mode == newValue) return;
            Mode = newValue;
            Calculate();
            NotifyPortValueChanged(ResultPort);
        }

        protected override object GetValueForPort(RuntimePort port) {
            if (port == ResultPort) return Result;
            return null;
        }

        protected override void OnPortValueChanged(Connection connection, RuntimePort port) {
            if (port == ResultPort) return;
            if (port == InputPort) {
                var newValue = GetValue(InputPort, Input);
                Input = newValue;
                Calculate();
                NotifyPortValueChanged(ResultPort);
            } else if (port == TranslationPort) {
                var newValue = GetValue(TranslationPort, Translation);
                if(math.distancesq(Translation, newValue) < Constants.FLOAT_TOLERANCE * Constants.FLOAT_TOLERANCE) return;
                Translation = newValue;
                Calculate();
                NotifyPortValueChanged(ResultPort);
            } else if (port == AttributeNamePort) {
                var newValue = GetValue(AttributeNamePort, AttributeName);
                if(string.Equals(AttributeName, newValue, StringComparison.InvariantCulture)) return;
                AttributeName = newValue;
                Calculate();
                NotifyPortValueChanged(ResultPort);
            }
        }

        public override string GetCustomData() {
            return new JArray {
                JsonConvert.SerializeObject(Translation, float3Converter.Converter),
                AttributeName,
                (int)Mode,
            }.ToString(Formatting.None);
        }

        public override void SetCustomData(string data) {
            JArray array = JArray.Parse(data);
            Translation = JsonConvert.DeserializeObject<float3>(array.Value<string>(0), float3Converter.Converter);
            AttributeName = array.Value<string>(1);
            Mode = (TranslatePointNode_Mode) array.Value<int>(2);

            Calculate();
            NotifyPortValueChanged(ResultPort);
        }
    }
}